######################################################################
# Automatically generated by qmake (3.0) ?? 3? 26 16:45:13 2014
######################################################################
QT += qml quick
TEMPLATE = app
TARGET = chapter-line
INCLUDEPATH += .

# Input
HEADERS += linechart.h
SOURCES += linechart.cpp main.cpp
#RESOURCES += qml.qrc
#OTHER_FILES += \
#    app.qml

RESOURCES += \
    qml.qrc
